version: '3.8'

services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mystorage
    ports:
      - "3306:3306"

